from __future__ import annotations

_LIGHTING_PRESET_NEUTRAL_HEMISPHERE = "neutral_hemisphere"
_ALLOWED_LIGHTING_PRESETS = (_LIGHTING_PRESET_NEUTRAL_HEMISPHERE,)
_ALLOWED_SHADOW_CUBE_SIZES = ("512", "1024", "2048", "4096")
_ALLOWED_RENDER_ENGINES = ("raster",)
_PEMOIN_LIGHTING_TAG = "pemoin_scene_light"
_PEMOIN_LIGHT_PLACEMENT_MODE = "pemoin_light_placement_mode"
_PEMOIN_LIGHT_PLACEMENT_TARGET = "pemoin_light_placement_target"
_PEMOIN_LIGHT_RELATIVE_OFFSET = "pemoin_light_relative_offset"
_PEMOIN_LIGHT_TRANSPORT_MODE = "pemoin_light_transport_mode"
_PEMOIN_LIGHT_SOURCE_ENERGY = "pemoin_light_source_energy"
_PEMOIN_LIGHT_REALIZED_ENERGY = "pemoin_light_realized_energy"
_WRAP_SUBJECT_FILL_TRANSPORT_MODE = "wrap_subject_fill"
_WRAP_SUBJECT_POINT_MIN_DISTANCE_M = 1.0

DEFAULT_SHOW_CHARACTER_LOGS = False
DEFAULT_SHOW_RENDER_LOGS = False
DEFAULT_SHOW_OVERLAY_LOGS = False
DEFAULT_SHOW_ROAD_PLANE_LOGS = True
DEFAULT_SHOW_ROAD_PLANE_FRAME_LOGS = True

_OVERLAY_ALPHA_THRESHOLD = 0.05
_SOLE_OFFSET_M = 0.06
_OVERLAY_FAIL_MEDIAN_SUPPORT_TO_CONTACT_FOOT_PX = 10.0
_OVERLAY_FAIL_P90_SUPPORT_TO_CONTACT_FOOT_PX = 18.0
_OVERLAY_FAIL_SINGLE_SUPPORT_TO_CONTACT_FOOT_PX = 20.0
_OVERLAY_FAIL_SOFT_SUPPORT_TO_CONTACT_FOOT_PX = 12.0
_OVERLAY_FAIL_MAX_FLAGGED_RATIO = 0.25
_OVERLAY_FAIL_MIN_ROAD_FRACTION = 0.20
_OVERLAY_WARN_SUPPORT_TO_SILHOUETTE_PX = 40.0
_LOCAL_SUPPORT_MAX_RESIDUAL_P90_M = 0.12
_LOCAL_SUPPORT_MIN_INLIER_RATIO = 0.55
_LOCAL_SUPPORT_MAX_PRE_SUPPORT_DIST_M = 0.35
_PERSISTED_BLEND_MAX_DISAGREEMENT_M = 0.18
_PERSISTED_BLEND_MIN_CONFIDENCE_FOR_PROJECTION = 0.25
_SUPPORT_MAX_NORMAL_JUMP_DEG = 3.0
_SUPPORT_MAX_HEIGHT_JUMP_M = 0.08
_SUPPORT_MAX_ANCHOR_SHIFT_M = 0.30
_OVERLAY_SUPPORT_PATCH_RADIUS_PX = 6
_OVERLAY_SUPPORT_LOCAL_GRID_EXTENT_M = 2.0
_OVERLAY_SUPPORT_LOCAL_GRID_SPACING_M = 0.2
_OVERLAY_SUPPORT_LOCAL_GRID_LINE_COLOR_BGR = (96, 240, 128)
_OVERLAY_SUPPORT_LOCAL_GRID_LINE_THICKNESS = 1
